language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
    - BYOND_MINOR="1346"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - DM_MAPFILE=""
    matrix:
    - BUILD_TOOLS=true
    - DM_MAPFILE="tgstation2"

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip


before_install:
  - chmod +x tools/travis/install_build_tools.sh

install:
  - bash tools/travis/install_build_tools.sh

before_script:
  - bash tools/travis/before_build_tools.sh
  - bash tools/travis/before_build_byond.sh

script:
  - bash tools/travis/check_filedirs.sh tgstation.dme
  - bash tools/travis/build_tools.sh
  - bashtools/travis/build_byond.sh

